version: 0.2

batch:
  fast-fail: false 
  build-fanout:
    parallelism: 5
    ignore-failure: false
    
phases:
  build:
    commands:
      - cd my-app
      - codebuild-glob-search '**/*.java'
      - codebuild-tests-run --test-command 'mvn test -Dtest=' --files-search "codebuild-glob-search '**/test/**/*.java'|tr -d ' '" --sharding-strategy 'equal-distribution'

  post_build:
    commands:
      - codebuild-glob-search '**/*.java'  
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"

reports:
  test-reports:
    files:
      - '**/junit.xml'               
    base-directory: .
    discard-paths: yes           
    file-format: JUNITXML
