version: 0.2

batch:
  fast-fail: false 
  build-fanout:
    parallelism: 5
    ignore-failure: false
    
phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/my-app
      - mvn install

  post_build:
    commands:
      - codebuild-glob-search '**/*.java'  
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"

reports:
  test-reports:
    files:
      - '**/junit.xml'               
    base-directory: .
    discard-paths: yes           
    file-format: JUNITXML
