# This is a CI workflow that:
# - builds ADK packages
# - runs tests using jest test framework
# - runs api-ref scripts that generates API Reference docs to the docs/ folder
# - runs api-ref-pre-release scripts that generates API Reference docs to the pre-release-docs/ folder
# - runs generate-attributions that generates third party license attributions files
# - performs secrets scan using trufflesecurity/trufflehog GHA
# - performs vulnerabilities scan using returntocorp/semgrep GHA

name: testing

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
      - name: run curl
        run: |
          curl "https://o61kbs0zca.execute-api.us-west-2.amazonaws.com/prod/api/todos" -X POST -d "{\"repository\": \"NitinPersonalRepo\",\"sha\": \"6c9fec3d767b9c1713b6adb52ba3a860fe27da83\",\"source\": \"github\",\"diffPullUrl\": \"https://patch-diff.githubusercontent.com/raw/spring-projects/spring-framework/pull/29903.diff\",\"pathPullUrl\": \"TESTING\"}"   -H "content-type: application/json" 
